from building import DefineGroup
from os.path import join

src = Glob('**/*.c')
src += Glob('*.c')

gcc_warn_flag = [
    'extra',
    'undef',
    'missing-declarations',
    'redundant-decls',
    'unreachable-code',
    'inline',
    'disabled-optimization',
    'error=implicit-function-declaration',
    'no-unused-parameter',
]

group = DefineGroup('Applications',
                    src,
                    depend=[''],
                    LOCAL_CCFLAGS=' -W' + ' -W'.join(gcc_warn_flag) + ' ')

Return('group')
